/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab33;

import java.util.HashSet;

public class Library {
    public String repeatedWord(String inputWord) {

        String[] wordArray = inputWord.split("\\s*(=>|,|\\s)\\s*");
        HashSet hashSet = new HashSet();

        for (int i = 0; i < wordArray.length; i++) {
            if (hashSet.contains(wordArray[i])) {
                return wordArray[i];
            } else {
                hashSet.add(wordArray[i].toLowerCase());
            }
        }
        return null;
    }


}
